before:
  hooks:
    - go mod tidy
    - go mod download

builds:
- 
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - 386
  env:
  - CGO_ENABLED=0
  ldflags:
  - -X github.com/olegsu/kubectl-fatch/cmd.version={{.Version}}

archives:
- 
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


release:
  github:
    owner: olegsu
    name: kubectl-fetch