apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: fetch-yaml
spec:
  version: "v0.2.0"
  homepage: https://github.com/olegsu/kubectl-fetch-yaml
  shortDescription: "Fetch Kubernetes files from remote destinations"
  description: |
    Fetch Kubernetes files from remote destinations
    Example git: kubectl fetch-yaml git --repo \
    https://github.com/kubernetes/examples --path guestbook/all-in-one | \
    kubectl apply -f -
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/olegsu/kubectl-fetch-yaml/releases/download/v0.2.0/kubectl-fetch-yaml_0.2.0_Darwin_x86_64.tar.gz
      sha256: e9437eef1fbe2c535a21fbc894d2ce1e1b68a4cf64212c58b4e247f6fd0a105f
      bin: "./kubectl-fetch-yaml"
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/olegsu/kubectl-fetch-yaml/releases/download/v0.2.0/kubectl-fetch-yaml_0.2.0_Linux_x86_64.tar.gz
      bin: "./kubectl-fetch-yaml"
      sha256: 35e3d2d96f832e13483baa384f0adec6c186cf6df65a30dd1f915a7ff9d5a4fe